# Generated by Django 5.2.8 on 2025-12-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universitysystem", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="curso",
            old_name="Descricao",
            new_name="descricao",
        ),
        migrations.RenameField(
            model_name="curso",
            old_name="Horarios",
            new_name="horarios",
        ),
        migrations.RenameField(
            model_name="curso",
            old_name="Instituicao",
            new_name="instituicao",
        ),
        migrations.RenameField(
            model_name="curso",
            old_name="Nome",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="curso",
            old_name="Sigla",
            new_name="sigla",
        ),
        migrations.RenameField(
            model_name="disciplina",
            old_name="Codigo",
            new_name="codigo",
        ),
        migrations.RenameField(
            model_name="disciplina",
            old_name="Curso",
            new_name="curso",
        ),
        migrations.RenameField(
            model_name="disciplina",
            old_name="Descricao",
            new_name="descricao",
        ),
        migrations.RenameField(
            model_name="disciplina",
            old_name="Nome",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="instituicao",
            old_name="CNPJ",
            new_name="cnpj",
        ),
        migrations.RenameField(
            model_name="instituicao",
            old_name="Endereco",
            new_name="endereco",
        ),
        migrations.RenameField(
            model_name="instituicao",
            old_name="Nome",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="instituicao",
            old_name="Sigla",
            new_name="sigla",
        ),
        migrations.AddField(
            model_name="usuario",
            name="matricula",
            field=models.CharField(
                default=0, max_length=50, unique=True, verbose_name="Matrícula"
            ),
            preserve_default=False,
        ),
    ]
