# Generated by Django 5.2.8 on 2025-11-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitysystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='funcao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(choices=[('AL', 'Aluno'), ('PR', 'Professor'), ('CO', 'Coordenador')], default='AL', max_length=2, verbose_name='Função'),
        ),
    ]
