# Generated by Django 5.2.8 on 2025-12-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universitysystem", "0002_rename_descricao_curso_descricao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="matricula",
            field=models.CharField(max_length=50, verbose_name="Matrícula"),
        ),
        migrations.CreateModel(
            name="CalendarioAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_referencia",
                    models.DateField(verbose_name="Data de Referência"),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Calendário Acadêmico 2025.2",
                        max_length=100,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "instituicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="universitysystem.instituicao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendário Acadêmico",
                "verbose_name_plural": "Calendários Acadêmicos",
                "ordering": ["-data_referencia"],
            },
        ),
        migrations.CreateModel(
            name="Compromisso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                ("data", models.DateField(verbose_name="Data do Compromisso")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FE", "Feriado"),
                            ("IA", "Início das Aulas"),
                            ("FA", "Fim das Aulas"),
                            ("PR", "Prova"),
                            ("EV", "Evento"),
                            ("RE", "Recesso"),
                        ],
                        default="EV",
                        max_length=2,
                        verbose_name="Tipo do Compromisso",
                    ),
                ),
                (
                    "calendario_academico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compromissos",
                        to="universitysystem.calendarioacademico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compromisso",
                "verbose_name_plural": "Compromissos",
                "ordering": ["data"],
            },
        ),
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emissao", models.DateField(auto_now=True)),
                (
                    "aluno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="universitysystem.aluno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestauranteUniversitario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cardapio_dia", models.TextField(verbose_name="Cardápio do Dia")),
                (
                    "horario_funcionamento",
                    models.TextField(verbose_name="Horário de Funcionamento"),
                ),
                ("precos", models.TextField(verbose_name="Tabela de Preços")),
                (
                    "instituicao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="universitysystem.instituicao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurante Universitário",
            },
        ),
        migrations.CreateModel(
            name="ItemHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Média Final"
                    ),
                ),
                (
                    "periodo_cursado",
                    models.CharField(help_text="Ex: 2025.2", max_length=6),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="universitysystem.disciplina",
                    ),
                ),
                (
                    "historico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="universitysystem.historico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Histórico",
                "verbose_name_plural": "Itens do Histórico",
                "unique_together": {("historico", "disciplina")},
            },
        ),
    ]
