# Generated by Django 5.2.8 on 2025-12-10 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universitysystem", "0003_alter_aluno_matricula_calendarioacademico_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restauranteuniversitario",
            name="cardapio_dia",
        ),
        migrations.AddField(
            model_name="aluno",
            name="curso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="universitysystem.curso",
                verbose_name="Curso",
            ),
        ),
        migrations.AddField(
            model_name="restauranteuniversitario",
            name="almoco",
            field=models.TextField(
                blank=True, default="Não informado", verbose_name="Almoço"
            ),
        ),
        migrations.AddField(
            model_name="restauranteuniversitario",
            name="cafe_manha",
            field=models.TextField(
                blank=True, default="Não informado", verbose_name="Café da Manhã"
            ),
        ),
        migrations.AddField(
            model_name="restauranteuniversitario",
            name="jantar",
            field=models.TextField(
                blank=True, default="Não informado", verbose_name="Jantar"
            ),
        ),
    ]
