# Generated by Django 5.2.8 on 2025-12-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "universitysystem",
            "0004_remove_restauranteuniversitario_cardapio_dia_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aluno",
            options={
                "ordering": ["nome_completo"],
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
            },
        ),
        migrations.AlterModelOptions(
            name="curso",
            options={
                "ordering": ["instituicao__nome", "nome"],
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
            },
        ),
        migrations.AlterModelOptions(
            name="disciplina",
            options={
                "ordering": ["curso__instituicao__nome", "curso__nome", "nome"],
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
            },
        ),
        migrations.AlterModelOptions(
            name="historico",
            options={"verbose_name": "Histórico", "verbose_name_plural": "Históricos"},
        ),
        migrations.AlterModelOptions(
            name="instituicao",
            options={
                "ordering": ["nome"],
                "verbose_name": "Instituição",
                "verbose_name_plural": "Instituições",
            },
        ),
        migrations.AlterModelOptions(
            name="restauranteuniversitario",
            options={
                "verbose_name": "Restaurante Universitário",
                "verbose_name_plural": "Restaurantes Universitários",
            },
        ),
        migrations.AlterModelOptions(
            name="turma",
            options={
                "ordering": ["-periodo", "nome"],
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
            },
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "ordering": ["first_name", "username"],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.AlterField(
            model_name="curso",
            name="horarios",
            field=models.CharField(max_length=32, verbose_name="Horários"),
        ),
        migrations.AlterField(
            model_name="curso",
            name="instituicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="universitysystem.instituicao",
                verbose_name="Instituição",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="funcao",
            field=models.CharField(
                choices=[
                    ("AL", "Aluno"),
                    ("PR", "Professor"),
                    ("CO", "Coordenador"),
                    ("AD", "Admin"),
                ],
                default="AL",
                max_length=2,
                verbose_name="Função",
            ),
        ),
    ]
