# Generated by Django 5.2.8 on 2025-12-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universitysystem", "0005_alter_aluno_options_alter_curso_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turma",
            name="periodo",
            field=models.CharField(verbose_name="Período"),
        ),
    ]
