# Generated by Django 5.2.8 on 2025-12-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitysystem', '0006_alter_turma_periodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome_completo',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
