# Generated by Django 5.2.8 on 2025-12-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitysystem', '0007_alter_aluno_options_remove_aluno_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_alunos/'),
        ),
    ]
