# Generated by Django 5.2.8 on 2025-12-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "universitysystem",
            "0009_turma_disciplina_aula_anexo_aviso_coordenador_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professor",
            options={"verbose_name": "Professor", "verbose_name_plural": "Professores"},
        ),
        migrations.RemoveField(
            model_name="professor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="nome_completo",
        ),
        migrations.AddField(
            model_name="professor",
            name="curso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="universitysystem.curso",
                verbose_name="Curso",
            ),
        ),
    ]
