# Generated by Django 5.2.8 on 2025-12-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "universitysystem",
            "0010_alter_professor_options_remove_professor_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Ativa"),
                    ("T", "Trancada"),
                    ("D", "Desativada"),
                    ("C", "Concluida"),
                ],
                default="A",
                max_length=1,
                verbose_name="Status da Matrícula",
            ),
        ),
    ]
