# Generated by Django 5.2.8 on 2025-12-12 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitysystem', '0011_professor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitysystem.aula')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaDeAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitysystem.aluno')),
                ('frequenciaAssociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universitysystem.frequencia')),
            ],
        ),
    ]
