# Generated by Django 5.2.8 on 2025-12-12 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universitysystem", "0012_frequencia_frequenciadeaula"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inscricaodealuno",
            options={
                "verbose_name": "Inscrição de Aluno",
                "verbose_name_plural": "Inscrições de Alunos",
            },
        ),
        migrations.AddField(
            model_name="turma",
            name="professor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="universitysystem.professor",
            ),
        ),
    ]
